name: Commitlint
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lints commits
        uses: wagoid/commitlint-github-action@v1
